sudo: required 
dist: trusty 
language: generic 
compiler:
  - gcc
env:
  matrix:
    - USE_DEB=true ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu NOT_TEST_BUILD=true NOT_TEST_INSTALL=true
install:
  - sudo apt-get install python-pip
  - sudo pip install netCDF4
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config  
script: 
  - source .ci_config/travis.sh