cartesian_controller:
  # Publish Rate in [Hz] of the torque commands
  publish_rate: 100
  # Joint Torque controller gains
  gains:
    #    X trans    Y trans   Z trans   X rot   Y rot   Z rot
    Kp: [3000.0,    3000.0,   3000.0,   100.0,   100.0,   100.0]
    Kd: [50.0,      50.0,    50.0,     10.0,    10.0,    10.0]
  # Information about the links to be used on the gravity induced torques calculation
  limits:
    x:
      min: -100
      max: 100
    y:
      min: -100
      max: 100
    z:
      min: -100
      max: 100
