output_mapping:
  x:
    axes:
      name:
        - right_y
      gain:
        - 1
  y:
    axes:
      name:
        - right_x
      gain:
        - 1
  z:
    axes:
      name:
        - left_y
      gain:
        - 1
  roll:
    buttons:
      name:
        - cross_left
        - cross_right
      gain:
        - -1
        - 1
  pitch:
    buttons:
      name:
        - cross_up
        - cross_down
      gain:
        - 1
        - -1
  yaw:
    axes:
      name:
        - left_x
      gain:
        - 1
