# Position controller
azimuth:
    effort_controller:
        type: effort_controllers/JointEffortController
        joint: azimuth
        pid: {p: 10000, i: 0, d: 10}

shoulder:
    effort_controller:
        type: effort_controllers/JointEffortController
        joint: shoulder
        pid: {p: 10000, i: 0, d: 10}

elbow:
    effort_controller:
        type: effort_controllers/JointEffortController
        joint: elbow
        pid: {p: 10000, i: 0, d: 10}

roll:
    effort_controller:
        type: effort_controllers/JointEffortController
        joint: roll
        pid: {p: 10000, i: 0, d: 10}

pitch:
    effort_controller:
        type: effort_controllers/JointEffortController
        joint: pitch
        pid: {p: 10000, i: 0, d: 10}

wrist:
    effort_controller:
        type: effort_controllers/JointEffortController
        joint: wrist
        pid: {p: 10000, i: 0, d: 10}
