# Position controller
azimuth:
    position_controller:
        type: effort_controllers/JointPositionController
        joint: azimuth
        pid: {p: 50000.0, i: 0.0, d: 500.0}

shoulder:
    position_controller:
        type: effort_controllers/JointPositionController
        joint: shoulder
        pid: {p: 50000.0, i: 7.0, d: 500.0}

elbow:
    position_controller:
        type: effort_controllers/JointPositionController
        joint: elbow
        pid: {p: 10000.0, i: 1.0, d: 10.0}

roll:
    position_controller:
        type: effort_controllers/JointPositionController
        joint: roll
        pid: {p: 10000.0, i: 2.0, d: 50.0}

pitch:
    position_controller:
        type: effort_controllers/JointPositionController
        joint: pitch
        pid: {p: 400.0, i: 3.0, d: 50.0}

wrist:
    position_controller:
        type: effort_controllers/JointPositionController
        joint: wrist
        pid: {p: 600.0, i: 0.01, d: 50.0}
