cartesian_controller:
  teleop:
    deadman_button: 'right'
    x:
      axes: 'right_y'
    y:
      axes: 'right_x'
    z:
      axes: 'left_y'
    pitch:
      up:
        buttons: 'cross_up'
      down:
        buttons: 'cross_down'
    yaw:
      up:
        buttons: 'cross_left'
      down:
        buttons: 'cross_right'
